# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ATMega_Block_Diagram.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt
from PyQt5.QtWidgets import QWidget, QLabel, QSplitter, QApplication, QHBoxLayout, QGroupBox, QFrame, QVBoxLayout, QStackedLayout


class Ui_microcontrollerBlock(object):
    def setupUi(self, microcontrollerBlock):
        microcontrollerBlock.setObjectName("microcontrollerBlock")
        microcontrollerBlock.resize(740, 575)
        microcontrollerBlock.setFrameShape(QtWidgets.QFrame.StyledPanel)
        microcontrollerBlock.setFrameShadow(QtWidgets.QFrame.Raised)
        self.tc0Frame = QtWidgets.QFrame(microcontrollerBlock)
        self.tc0Frame.setGeometry(QtCore.QRect(480, 240, 120, 80))
        self.tc0Frame.setStyleSheet("background-color: rgb(114, 159, 207);")
        self.tc0Frame.setFrameShape(QtWidgets.QFrame.Panel)
        self.tc0Frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.tc0Frame.setLineWidth(2)
        self.tc0Frame.setObjectName("tc0Frame")
        self.tc0Label = QtWidgets.QLabel(self.tc0Frame)
        self.tc0Label.setGeometry(QtCore.QRect(30, 20, 67, 41))
        self.tc0Label.setScaledContents(False)
        self.tc0Label.setAlignment(QtCore.Qt.AlignCenter)
        self.tc0Label.setWordWrap(True)
        self.tc0Label.setObjectName("tc0Label")
        self.watchdogFrame = QtWidgets.QFrame(microcontrollerBlock)
        self.watchdogFrame.setGeometry(QtCore.QRect(130, 150, 120, 80))
        self.watchdogFrame.setStyleSheet("background-color: rgb(114, 159, 207);")
        self.watchdogFrame.setFrameShape(QtWidgets.QFrame.Panel)
        self.watchdogFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.watchdogFrame.setLineWidth(2)
        self.watchdogFrame.setObjectName("watchdogFrame")
        self.watchdogLabel = QtWidgets.QLabel(self.watchdogFrame)
        self.watchdogLabel.setGeometry(QtCore.QRect(16, 20, 91, 41))
        self.watchdogLabel.setScaledContents(False)
        self.watchdogLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.watchdogLabel.setWordWrap(True)
        self.watchdogLabel.setObjectName("watchdogLabel")
        self.tc2Frame = QtWidgets.QFrame(microcontrollerBlock)
        self.tc2Frame.setGeometry(QtCore.QRect(130, 400, 120, 80))
        self.tc2Frame.setStyleSheet("background-color: rgb(114, 159, 207);")
        self.tc2Frame.setFrameShape(QtWidgets.QFrame.Panel)
        self.tc2Frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.tc2Frame.setLineWidth(2)
        self.tc2Frame.setObjectName("tc2Frame")
        self.tc2Label = QtWidgets.QLabel(self.tc2Frame)
        self.tc2Label.setGeometry(QtCore.QRect(30, 20, 67, 41))
        self.tc2Label.setScaledContents(False)
        self.tc2Label.setAlignment(QtCore.Qt.AlignCenter)
        self.tc2Label.setWordWrap(True)
        self.tc2Label.setObjectName("tc2Label")
        self.usartFrame = QtWidgets.QFrame(microcontrollerBlock)
        self.usartFrame.setGeometry(QtCore.QRect(300, 360, 120, 80))
        self.usartFrame.setStyleSheet("background-color: rgb(114, 159, 207);")
        self.usartFrame.setFrameShape(QtWidgets.QFrame.Panel)
        self.usartFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.usartFrame.setLineWidth(2)
        self.usartFrame.setObjectName("usartFrame")
        self.usartLabel = QtWidgets.QLabel(self.usartFrame)
        self.usartLabel.setGeometry(QtCore.QRect(30, 30, 67, 17))
        self.usartLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.usartLabel.setObjectName("usartLabel")
        self.flashFrame = QtWidgets.QFrame(microcontrollerBlock)
        self.flashFrame.setGeometry(QtCore.QRect(300, 90, 120, 80))
        self.flashFrame.setStyleSheet("background-color: rgb(114, 159, 207);")
        self.flashFrame.setFrameShape(QtWidgets.QFrame.Panel)
        self.flashFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.flashFrame.setLineWidth(2)
        self.flashFrame.setObjectName("flashFrame")
        self.flashLabel = QtWidgets.QLabel(self.flashFrame)
        self.flashLabel.setGeometry(QtCore.QRect(20, 30, 67, 17))
        self.flashLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.flashLabel.setObjectName("flashLabel")
        self.gpiorFrame = QtWidgets.QFrame(microcontrollerBlock)
        self.gpiorFrame.setGeometry(QtCore.QRect(480, 130, 120, 80))
        self.gpiorFrame.setStyleSheet("background-color: rgb(114, 159, 207);")
        self.gpiorFrame.setFrameShape(QtWidgets.QFrame.Panel)
        self.gpiorFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.gpiorFrame.setLineWidth(2)
        self.gpiorFrame.setObjectName("gpiorFrame")
        self.gpiorLabel = QtWidgets.QLabel(self.gpiorFrame)
        self.gpiorLabel.setGeometry(QtCore.QRect(20, 20, 67, 41))
        self.gpiorLabel.setScaledContents(False)
        self.gpiorLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.gpiorLabel.setWordWrap(True)
        self.gpiorLabel.setObjectName("gpiorLabel")
        self.spiFrame = QtWidgets.QFrame(microcontrollerBlock)
        self.spiFrame.setGeometry(QtCore.QRect(480, 390, 120, 80))
        self.spiFrame.setStyleSheet("background-color: rgb(114, 159, 207);")
        self.spiFrame.setFrameShape(QtWidgets.QFrame.Panel)
        self.spiFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.spiFrame.setLineWidth(2)
        self.spiFrame.setObjectName("spiFrame")
        self.spiLabel = QtWidgets.QLabel(self.spiFrame)
        self.spiLabel.setGeometry(QtCore.QRect(30, 20, 67, 41))
        self.spiLabel.setScaledContents(False)
        self.spiLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.spiLabel.setWordWrap(True)
        self.spiLabel.setObjectName("spiLabel")
        self.tc1Frame = QtWidgets.QFrame(microcontrollerBlock)
        self.tc1Frame.setGeometry(QtCore.QRect(130, 280, 120, 80))
        self.tc1Frame.setStyleSheet("background-color: rgb(114, 159, 207);")
        self.tc1Frame.setFrameShape(QtWidgets.QFrame.Panel)
        self.tc1Frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.tc1Frame.setLineWidth(2)
        self.tc1Frame.setObjectName("tc1Frame")
        self.tc1Label = QtWidgets.QLabel(self.tc1Frame)
        self.tc1Label.setGeometry(QtCore.QRect(30, 20, 67, 41))
        self.tc1Label.setScaledContents(False)
        self.tc1Label.setAlignment(QtCore.Qt.AlignCenter)
        self.tc1Label.setWordWrap(True)
        self.tc1Label.setObjectName("tc1Label")
        self.eepromFrame = QtWidgets.QFrame(microcontrollerBlock)
        self.eepromFrame.setGeometry(QtCore.QRect(300, 210, 120, 80))
        self.eepromFrame.setStyleSheet("background-color: rgb(114, 159, 207);")
        self.eepromFrame.setFrameShape(QtWidgets.QFrame.Panel)
        self.eepromFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.eepromFrame.setLineWidth(2)
        self.eepromFrame.setObjectName("eepromFrame")
        self.eepromLabel = QtWidgets.QLabel(self.eepromFrame)
        self.eepromLabel.setGeometry(QtCore.QRect(30, 30, 67, 17))
        self.eepromLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.eepromLabel.setObjectName("eepromLabel")

        self.retranslateUi(microcontrollerBlock)
        QtCore.QMetaObject.connectSlotsByName(microcontrollerBlock)

    def retranslateUi(self, microcontrollerBlock):
        _translate = QtCore.QCoreApplication.translate
        microcontrollerBlock.setWindowTitle(_translate("microcontrollerBlock", "Frame"))
        self.tc0Label.setText(_translate("microcontrollerBlock", "TC 0            (8-bit)"))
        self.watchdogLabel.setText(_translate("microcontrollerBlock", "Watchdog timer"))
        self.tc2Label.setText(_translate("microcontrollerBlock", "TC 2            (8-bit)"))
        self.usartLabel.setText(_translate("microcontrollerBlock", "USART 0"))
        self.flashLabel.setText(_translate("microcontrollerBlock", "Flash"))
        self.gpiorLabel.setText(_translate("microcontrollerBlock", "GPIOR [2:0]"))
        self.spiLabel.setText(_translate("microcontrollerBlock", "SPI 0            (8-bit)"))
        self.tc1Label.setText(_translate("microcontrollerBlock", "TC 1            (8-bit)"))
        self.eepromLabel.setText(_translate("microcontrollerBlock", "EEPROM"))


